name: Fixility CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔐 Login met je persoonlijke token (die GHCR_PAT heet in Secrets)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 01-UI/ZorgmeldSysteem.WebApi/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/zorgmeldsysteem-api:latest

