name: Fixility CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Zorgmeldsysteem API
        uses: docker/build-push-action@v5
        with:
          context: ./01-UI/ZorgmeldSysteem.WebApi
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/zorgmeldsysteem-api:latest

